### ISSUE TITLE
Still getting error: WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by rzubrycki** [dweirich/gatsby-plugin-react-leaflet#5]
Hello, i have a problem when trying to build production version of my app.
I'm getting this error message:

<img width="604" alt="Screenshot 2019-03-12 at 13 07 24" src="https://user-images.githubusercontent.com/20592163/54198881-d852da80-44c7-11e9-83ce-c4172844b20e.png">

this is my component with map:

<img width="524" alt="Screenshot 2019-03-12 at 13 07 05" src="https://user-images.githubusercontent.com/20592163/54198912-e7d22380-44c7-11e9-8269-61b6e1c84561.png">

I'm using gatsby-plugin-react-leaflet but without success.

**Comment by ovsw** [comment]
+1 getting the exact same thing

The updated code for Gatsby v2 isn't working, the react-leaflet module is being processed by webpack, and that's what's causing the error. 

Basically this plugin now does nothing, since that was its whole purpose.

Tried various workarounds but no luck so far.

**Comment by dweirich** [comment]
@rzubrycki This error is because you are importing the Leaflet library. This plugin fixes an error on build for the react-leaflet library by replacing it with a null loader. 

I've pushed an update to add leaflet to the null loader list, but you'll still have to wrap the icon code in a window check to get around the SSR.

**Comment by ovsw** [comment]
Thanks, that did it! 

Also, for anyone using **styled components** that build on any of the imported leaflet components, be aware it's not going to work (since the components won't exist, on build).

As a workaround, just use CSS modules or plain old style attribute to style them ( for example, the Map component, which requires a height attribute in order to show up).

**Comment by dagoss** [comment]
I ran into this issue using Leaflet directly (to customize marker icons). It wasn't obvious to me that required wrapping my code that called `L.icon(...)` to check that window is defined. Maybe this is something that could be added to the readme?
